<script type="text/javascript">

</script>
<body onload="time();">
	<div id="divBody">
		<div id="divSlide">
			<figure id="slide">

			</figure>
		</div>

		<div id="divTempo">
			<div id="tempo">
				<img id="logoIf" class="logos" alt="IFG" src="img/if.png">
				<div id="horaP"></div>
				<div id="dataP"><?php echo date("d/M/Y")?></div>
			</div>
		</div>

		<div>
			<div id="divLegenda">

			</div>
		</div>

		<div id="divLinkQr">
			<div id="linkQr"></div>
		</div>


		<div id="coment">
		 <figure id="imgPerfilComent"></figure>

		 <div id="nomeComent"></div>

		 <div id="textComent"></div>

		 <div id="infoComent"></div>


		</div>
	</div>

</body>
