<script type="text/javascript">

</script>
<body onload="time();">
	<div id="divBody">
		<div id="divSlide">
			<figure id="slide">

			</figure>
		</div>

		<div id="divTempo">
			<div id="tempo">
				<img id="logoIf" class="logos" alt="IFG" src="img/if.png">
				<div id="horaP"></div>
				<div id="dataP"><?php echo date("d/M/Y")?></div>
			</div>
		</div>

		<div>
			<div id="divLegenda">

			</div>
		</div>

		<div id="divLinkQr">
			<div id="linkQr"></div>
		</div>

		<div id="coment">
			<figure id="imgPerfilComent"></figure>
			<div id="nomeComent" align='center'></div>
			<div id="textComent" align='center'></div>
			<div id="infoComent" align='center'></div>
		</div>
	</div>

</body>
